### ISSUE TITLE
Missing CSV files

### ISSUE THREAD

**Issue by Eebbu** [asif-hanif/palm#1]
Hi, I noticed no train/test CSV file when I ran the experiments.
------------------------------------------------------------------
Running METHOD=palm on DATASET=UrbanSound8K
Running Fold-1 with SEED=0
cp: cannot stat 'palm/scripts/Audio-Datasets/UrbanSound8K/csv_files/train_1.csv': No such file or directory
cp: cannot stat 'palm/scripts/Audio-Datasets/UrbanSound8K/csv_files/test_1.csv': No such file or directory
python: can't open file 'main.py': [Errno 2] No such file or directory

**Comment by asif-hanif** [comment]
Hi @Eebbu 
Thank you for interest in our work.

Can you share the shell script you are trying to run?

I am assuming that you have already downloaded the dataset by following the [instructions](https://github.com/asif-hanif/palm/blob/main/DATASETS.md#urbansound8k).

Make sure that you are in the [`palm`](https://github.com/asif-hanif/palm) directory after cloning the repo and setting up the python environment. Once everything is setup, you are supposed to run following command (for METHOD='palm' and DATASET='UrbanSound8K')

`bash scripts/urban_sound.sh palm`

**Comment by Eebbu** [comment]
Hi, thank you for the quick response. I tried running the ` bash scripts/urban_sound.sh palm` and downloaded the [UrbanSound8K](https://urbansounddataset.weebly.com/urbansound8k.html) dataset following the instruction. I might have misunderstood the instructions. Do I need to download all the datasets? Also, do I need to create the CSV file mentioned [here](https://github.com/asif-hanif/palm/blob/main/DATASETS.md?plain=1#L36-L38) myself?

**Comment by asif-hanif** [comment]
You do not need to download all datasets. If you want to run experiments on UrbanSound8K, you need to download this dataset only. Secondly, csv files already exist in the downloaded dataset.
Thirdly, path of the dataset needs to be specified in the shell script. If you can share snapshots of errors and the shell script, it will be easier for me to pinpoint the underlying issue.

**Comment by Eebbu** [comment]
It was a mistake on my part; I didn’t successfully download the CSV file. The problem is now solved. Thank you!

**Comment by asif-hanif** [comment]
I've added `main.py` to the repository, which was previously omitted by mistake. Please re-clone the repo and verify if everything works. Feel free to reach out if you encounter any issues.

**Comment by YvoGao** [comment]
> It was a mistake on my part; I didn’t successfully download the CSV file. The problem is now solved. Thank you!

hello, I have a problem like yours, too. But I can't  download the whole dataset of NS-Instruments, TUT2017, UrbanSound8K, VocalSound

**Comment by asif-hanif** [comment]
Hi @YvoGao 
NS-Instruments and VocalSound have yet to be uploaded from our side. We face technical issues while uploading these datasets. We will fix it soon. Rest of the datasets can be downloaded from Huggingface with Python commands shared for each dataset in [DATASETS.md](https://github.com/asif-hanif/palm/blob/main/DATASETS.md). Please feel free to reach out if you encounter any issue/error while downloading the datasets.

**Comment by YvoGao** [comment]
In NS-Instruments dataset, there are only five classes:'bass', 'brass', 'flute', 'guitar', 'keyboard', missing another five classes: 'mallet', 'organ', 'reed', 'string', 'vocal']

**Comment by asif-hanif** [comment]
Hello @YvoGao 
Issue has been fixed. Please download the updated dataset.
