### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by YvoGao** [asif-hanif/palm#2]
may I have a cloud pan link to download datasets, hugging face is very difficult to download. Thank you very much.

**Comment by asif-hanif** [comment]
Hi @YvoGao 
Thanks for showing interest in our work.
Could you let me know the issues you are facing while downloading the datasets from Huggingface?
At this moment, we do not have cloud link to share.

**Comment by YvoGao** [comment]
Thank you for your reply.  I fix the download problem. I find NS-Instruments and VocalSound miss the context in hugging face. So will you put it in cloud pan soon?

**Comment by asif-hanif** [comment]
We will upload NS-Instruments and VocalSound within one week. I'll post an update here once the dataset upload is complete.

**Comment by YvoGao** [comment]
Thank you very much!!!

**Comment by asif-hanif** [comment]
Hi @YvoGao 
`NS-Instruments` and `VocalSound` datasets have been uploaded. Please refer to updated instructions o these datasets in [DATASETS.md](https://github.com/asif-hanif/palm/blob/main/DATASETS.md). Please let me know if you face any issue.

**Comment by YvoGao** [comment]
> Hi @YvoGao `NS-Instruments` and `VocalSound` datasets have been uploaded. Please refer to updated instructions o these datasets in [DATASETS.md](https://github.com/asif-hanif/palm/blob/main/DATASETS.md). Please let me know if you face any issue.


In NS-Instruments dataset, there are only five classes:'bass', 'brass', 'flute', 'guitar', 'keyboard', missing another five classes: 'mallet', 'organ', 'reed', 'string', 'vocal']

**Comment by asif-hanif** [comment]
Hi @YvoGao 
Could you please confirm if `NS-Instruments` dataset has been downloaded with following commands:

```python
import os
import zipfile
import shutil
import huggingface_hub
audio_datasets_path = "DATASET_PATH/Audio-Datasets"
if not os.path.exists(audio_datasets_path): print(f"Given {audio_datasets_path=} does not exist. Specify a valid path ending with 'Audio-Datasets' folder.")
huggingface_hub.snapshot_download(repo_id="MahiA/NS-Instruments", repo_type="dataset", local_dir=os.path.join(audio_datasets_path, "NS-Instruments"))
zipfile_path = os.path.join(audio_datasets_path, 'NS-Instruments', 'NS-Instruments.zip')
with zipfile.ZipFile(zipfile_path,"r") as zip_ref:
    zip_ref.extractall(os.path.join(audio_datasets_path, 'NS-Instruments'))
shutil.move(os.path.join(audio_datasets_path, 'NS-Instruments','NS-Instruments', 'audios'), os.path.join(audio_datasets_path, 'NS-Instruments'))
shutil.move(os.path.join(audio_datasets_path, 'NS-Instruments','NS-Instruments', 'train.csv'), os.path.join(audio_datasets_path, 'NS-Instruments'))
shutil.move(os.path.join(audio_datasets_path, 'NS-Instruments','NS-Instruments', 'test.csv'), os.path.join(audio_datasets_path, 'NS-Instruments'))
shutil.rmtree(os.path.join(audio_datasets_path, 'NS-Instruments', 'NS-Instruments'))
os.remove(zipfile_path)
```

**Comment by YvoGao** [comment]
yes, we use this. 
In hugging face web, we have downloaded the org NS-Instruments.zip, and there are no other five classes.

**Comment by asif-hanif** [comment]
We are trying to fix the issue and will update soon.

**Comment by asif-hanif** [comment]
Hi @YvoGao 
The issue has been resolved. Please try downloading the dataset again. 
The problem occurred due to an incomplete transfer from the compute cluster to the local machine, which resulted in an incomplete dataset being mistakenly uploaded. This has now been corrected.

**Comment by asif-hanif** [comment]
I hope you are able to download the full dataset. Feel free to reopen the issue if you encounter any issues.
